os: linux
dist: bionic

language: "go"

jobs:
  include:
    - language: go

      go: "1.13.x"
      env:
        global:
          GO111MODULE=on

      before_install:
        - go get github.com/mattn/goveralls

      script:
        - GOOS=linux GOARCH=amd64 go build -o pm5-emulator cmd/pm5-emulator/main.go
        - go test -v -race -covermode atomic -coverprofile="profile.cov" ./...
        - $HOME/gopath/bin/goveralls -coverprofile="profile.cov" -service=travis-ci
