package config

const (
	CSAFE_RESET_CMD      = 0x81
	CSAFE_GOIDLE_CMD     = 0x82
	CSAFE_GOHAVEID_CMD   = 0x83
	CSAFE_GOINUSE_CMD    = 0x85
	CSAFE_GOFINISHED_CMD = 0x86
	CSAFE_GOREADY_CMD    = 0x87
	CSAFE_BADID_CMD      = 0x88
)
