package config

//ERG MACHINE TYPE
const (
	ERGMACHINE_TYPE_STATIC_D             = 0
	ERGMACHINE_TYPE_STATIC_C             = 1
	ERGMACHINE_TYPE_STATIC_A             = 2
	ERGMACHINE_TYPE_STATIC_B             = 3
	ERGMACHINE_TYPE_STATIC_E             = 5
	ERGMACHINE_TYPE_STATIC_SIMULATOR     = 7
	ERGMACHINE_TYPE_STATIC_DYNAMIC       = 8
	ERGMACHINE_TYPE_SLIDES_A             = 16
	ERGMACHINE_TYPE_SLIDES_B             = 17
	ERGMACHINE_TYPE_SLIDES_C             = 18
	ERGMACHINE_TYPE_SLIDES_D             = 19
	ERGMACHINE_TYPE_SLIDES_E             = 20
	ERGMACHINE_TYPE_SLIDES_DYNAMIC       = 32
	ERGMACHINE_TYPE_STATIC_DYNO          = 64
	ERGMACHINE_TYPE_STATIC_SKI           = 128
	ERGMACHINE_TYPE_STATIC_SKI_SIMULATOR = 143
	ERGMACHINE_TYPE_BIKE                 = 192
	ERGMACHINE_TYPE_BIKE_ARMS            = 193
	ERGMACHINE_TYPE_BIKE_NOARMS          = 194
	ERGMACHINE_TYPE_BIKE_SIMULATOR       = 207
	ERGMACHINE_TYPE_NUM                  = 208
)

//Workout Type
const (
	WORKOUTTYPE_JUSTROW_NOSPLITS                = 0
	WORKOUTTYPE_JUSTROW_SPLITS                  = 1
	WORKOUTTYPE_FIXEDDIST_NOSPLITS              = 2
	WORKOUTTYPE_FIXEDDIST_SPLITS                = 3
	WORKOUTTYPE_FIXEDTIME_NOSPLITS              = 4
	WORKOUTTYPE_FIXEDTIME_SPLITS                = 5
	WORKOUTTYPE_FIXEDTIME_INTERVAL              = 6
	WORKOUTTYPE_FIXEDDIST_INTERVAL              = 7
	WORKOUTTYPE_VARIABLE_INTERVAL               = 8
	WORKOUTTYPE_VARIABLE_UNDEFINEDREST_INTERVAL = 9
	WORKOUTTYPE_FIXED_CALORIE                   = 10
	WORKOUTTYPE_FIXED_WATTMINUTES               = 11
	WORKOUTTYPE_FIXEDCALS_INTERVAL              = 12
	WORKOUTTYPE_NUM                             = 13
)

//Interval Type
const (
	INTERVALTYPE_TIME                    = 0
	INTERVALTYPE_DIST                    = 1
	INTERVALTYPE_REST                    = 2
	INTERVALTYPE_TIMERESTUNDEFINED       = 3
	INTERVALTYPE_DISTANCERESTUNDEFINED   = 4
	INTERVALTYPE_RESTUNDEFINED           = 5
	INTERVALTYPE_CAL                     = 6
	INTERVALTYPE_CALRESTUNDEFINED        = 7
	INTERVALTYPE_WATTMINUTE              = 8
	INTERVALTYPE_WATTMINUTERESTUNDEFINED = 9
	INTERVALTYPE_NONE                    = 255
)

//Workout State
const (
	WORKOUTSTATE_WAITTOBEGIN                   = 0
	WORKOUTSTATE_WORKOUTROW                    = 1
	WORKOUTSTATE_COUNTDOWNPAUSE                = 2
	WORKOUTSTATE_INTERVALREST                  = 3
	WORKOUTSTATE_INTERVALWORKTIME              = 4
	WORKOUTSTATE_INTERVALWORKDISTANCE          = 5
	WORKOUTSTATE_INTERVALRESTENDTOWORKTIME     = 6
	WORKOUTSTATE_INTERVALRESTENDTOWORKDISTANCE = 7
	WORKOUTSTATE_INTERVALWORKTIMETOREST        = 8
	WORKOUTSTATE_INTERVALWORKDISTANCETOREST    = 9
	WORKOUTSTATE_WORKOUTEND                    = 10
	WORKOUTSTATE_TERMINATE                     = 11
	WORKOUTSTATE_WORKOUTLOGGED                 = 12
	WORKOUTSTATE_REARM                         = 13
)

//Rowing State
const (
	ROWINGSTATE_INACTIVE = 0
	ROWINGSTATE_ACTIVE   = 1
)

//Stroke State
const (
	STROKESTATE_WAITING_FOR_WHEEL_TO_REACH_MIN_SPEED_STATE = 0
	STROKESTATE_WAITING_FOR_WHEEL_TO_ACCELERATE_STATE      = 1
	STROKESTATE_DRIVING_STATE                              = 2
	STROKESTATE_DWELLING_AFTER_DRIVE_STATE                 = 3
	STROKESTATE_RECOVERY_STATE                             = 4
)

//Workout Duration Type
const (
	CSAFE_TIME_DURATION     = 0
	CSAFE_CALORIES_DURATION = 0X40
	CSAFE_DISTANCE_DURATION = 0X80
	CSAFE_WATTS_DURATION    = 0XC0
)

//GAME ID
const (
	APGLOBALS_GAMEID_NONE            = 0
	APGLOBALS_GAMEID_FISH            = 1
	APGLOBALS_GAMEID_DART            = 2
	APGLOBALS_GAMEID_TARGET_BASIC    = 3
	APGLOBALS_GAMEID_TARGET_ADVANCED = 4
	APGLOBALS_GAMEID_CROSSTRAINING   = 5
)
