package config

const (
	PM5_STATE_READY    = "READY"
	PM5_STATE_IDLE     = "IDLE"
	PM5_STATE_MANUAL   = "MANUAL"
	PM5_STATE_HAVEID   = "HAVEID"
	PM5_STATE_PAUSED   = "PAUSED"
	PM5_STATE_FINISHED = "FINISHED"
	PM5_STATE_INUSE    = "INUSE"
)
